Repository Miguelsiqueiros/El-Tempranon-Frontend, pull requests merged in 2020-02, with the labels that each got.

#42 Get API URL endpoint from env var
  config.js
  package.json
Labels: deployment

#45 Frontend/bugfixes from merge/ernesto
  src/app/app.module.ts
Labels: bug

#46 Change env var from API_URL to apiUrl
  config.js
Labels: bug

#47 Added the z-index property to navbar so it always appears on top
  src/app/app.component.css
Labels: bug

#53 Create unit tests for PTO and refactor PTO related code
  src/app/Models/pto.ts
  src/app/Services/pto.service.ts
  src/app/components/CreatePTO/CreatePTO.component.html
  src/app/components/CreatePTO/CreatePTO.component.spec.ts
  src/app/components/CreatePTO/CreatePTO.component.ts
Labels: Refactor, Unit Tests

#54 Finish PTO
  .vscode/launch.json
  src/app/components/CreatePTO/CreatePTO.component.html
  src/app/components/CreatePTO/CreatePTO.component.spec.ts
  src/app/components/CreatePTO/CreatePTO.component.ts
Labels: Unit Tests, enhancement

#57 Feature/nabvar unit test/antonio
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.spec.ts
Labels: Unit Tests

#58 Check-in Unit Test
  src/app/components/check-in/check-in.component.html
  src/app/components/check-in/check-in.component.spec.ts
Labels: Unit Tests

#61 Created dashboard page and added it cards of winners, losers and aver…
  package-lock.json
  package.json
  src/app/Models/lazyAndBest.ts
  src/app/Services/dashboard.service.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/card/card.component.css
  src/app/components/card/card.component.html
  src/app/components/card/card.component.spec.ts
  src/app/components/card/card.component.ts
  src/app/components/dashboard/dashboard.component.css
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.spec.ts
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/navbar/navbar.component.html
Labels: enhancement

#63 Ranking component unit test
  src/app/components/ranking/ranking.component.html
  src/app/components/ranking/ranking.component.spec.ts
Labels: Unit Tests
